"""Add members and inspirations tables

Revision ID: 3a72b656e1a0
Revises: 
Create Date: 2021-04-03 14:38:54.255587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a72b656e1a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('server', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inspirations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('server', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inspirations')
    op.drop_table('members')
    # ### end Alembic commands ###
