"""Updated sounds model and schema

Revision ID: 9af345d7fbb1
Revises: 6819b62a4e69
Create Date: 2021-05-04 20:39:07.909707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9af345d7fbb1'
down_revision = '6819b62a4e69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sounds', sa.Column('command', sa.String(), nullable=False))
    op.add_column('sounds', sa.Column('file_location', sa.String(), nullable=False))
    op.add_column('sounds', sa.Column('nsfw', sa.Boolean(), nullable=False))
    op.drop_column('sounds', 'name')
    op.drop_column('sounds', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sounds', sa.Column('location', sa.VARCHAR(), nullable=False))
    op.add_column('sounds', sa.Column('name', sa.VARCHAR(), nullable=False))
    op.drop_column('sounds', 'nsfw')
    op.drop_column('sounds', 'file_location')
    op.drop_column('sounds', 'command')
    # ### end Alembic commands ###
